baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Intro to Docker'
theme = "hugo-theme-relearn"

canonifyURLs = true

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

